version: '3.3'
services:
  nginx:
    network_mode: host
    container_name: nginx-proxy
    restart: always
    volumes:
      - '~/docker/nginx/certs:/etc/nginx/certs:ro'
      - '~/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro'
    image: nginx
